### ISSUE TITLE
Rework Commander Enhancements to be all viable & powerful

### ISSUE THREAD

**Issue by Azraeel** [LOUD-Community-Edition/LOUD-Community-Edition#4]

**Comment by loudpatches** [comment]
Original versions from the before time were forked [here](https://github.com/loudpatches/chadcomms).  Structural changes to the BO upgrade paths (pretty invasive) make it a bit of a taller order to get parity (if that's desired), but the weapon stats and damage and costs could be reverted close to the original values if desired.  There would likely be a bit of translation required (probably easiest to try to script it instead of hand jamming every weapon/stat). 

Even the legacy enhanced comms (while fun) had some criticism from its fans, but not to the point of the current incarnation.
