### ISSUE TITLE
Perhaps maybe rework overcharge to be more commonly used

### ISSUE THREAD

**Issue by Azraeel** [LOUD-Community-Edition/LOUD-Community-Edition#47]
Commander Overcharge right now is structured like vanilla which in turns allows you to one shot other commanders & sacus (you may see how this is a problem) however I'd prefer if it was more useful against units, aka reenabled more consistently then it does right now. This should be easy to do but I'm looking for feedback on it ofc.

**Comment by PurpleMossClump** [comment]
This seems like an easy one, with multiple solutions to implement depending on your desired effect.

1. Can give ACUs and SACUs damage resistance to Overcharge so they can't be one-hit-killed by it.
2. Can make ACU's death explosion deadlier, so that if one tries to use OC against an enemy ACU, it's guaranteed they'll both die. 

I'm sure there are other ways to go about it, but these 2 immediately came to mind.

**Comment by Azraeel** [comment]
1. FAF actually has a implemtation of this so I can look at that

@PurpleMossClump
